mail:
  source: Dominik Wojciechowski <t1@gmail.com>
  login: t1@gmail.com
  password: pass
  target :
    - t2@gmail.com
telegram:
  token: token
db:
  server: SRV_ADDR
  login: login
  password: passwd
  name: db