telegram:
  token: token
db:
  server: SRV_ADDR
  login: login
  password: passwd
  name: db

scheduler:
  daily:
    10-01:
      - xkom
      - alto
    22-01:
      - xkom
      - alto
    00-01:
      - combat
  every:
    15:
      - morele